version: "3.8"

services:
  mysql-server-1:
    image: mysql:8.0
    volumes:
        - db:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=password
volumes:
  db:
    driver: local